dist: xenial
language: cpp
copiler: clang
addons:
  apt:
   packages:
   - libboost-test-dev
   - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target packages
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.dev -ushebdim:$BINTRAY_APY_KEY "https://api.bintray.com/content/Rimkon/first_tutor/homework/$TRAVIS_BUILD_NUMBER/cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"  
